# Generated by Django 5.0.6 on 2024-05-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='url',
            new_name='dest_url',
        ),
    ]
