# Generated by Django 5.0.6 on 2024-05-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_qrcode', '0002_rename_url_customurl_dest_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customurl',
            unique_together={('assigned_object_type', 'assigned_object_id')},
        ),
    ]
