# Generated by Django 5.0.6 on 2024-05-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0003_alter_customurl_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesettings',
            name='name',
            field=models.CharField(default='default settings', max_length=200),
        ),
        migrations.AlterField(
            model_name='qrcodesettings',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
