# Generated by Django 5.0.6 on 2024-05-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_qrcode', '0004_qrcodesettings_name_alter_qrcodesettings_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCodeSettings',
            new_name='QRCodeSetting',
        ),
    ]
